CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number UUID                                    NOT NULL UNIQUE,
    sku_code     VARCHAR(255)                            NOT NULL,
    price        DECIMAL(19, 2)                          NOT NULL CHECK (price >= 0),
    quantity     INTEGER                                 NOT NULL CHECK (quantity > 0),
    created_at   TIMESTAMPTZ                             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ                             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);
